routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::resource('product', 'ProductController');
Route::get('profile', 'ProfileController@index')->name('profile.index');
Route::post('profile/{redirect}', 'ProfileController@update')->name('profile.redirect');

Route::middleware(['auth:sanctum', 'verified'])->get('/', function () {
    return view('pages.home');
})->name('home.auth');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'kategori', 'jumlah', 'harga', 'keterangan', 'image'
    ];

    protected $hidden = [

    ];

    public function getImageAttribute($name)
    {
        return asset('storage/' . $name);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();

        return view('pages.product.index',[
            'products' => $products,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $data = $request->all();

        $data['image'] = $request->file('image')->store('assets/product', 'public');

        Product::create($data);

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Product::findOrFail($id);
        return view('pages.product.edit', [
            'item' => $item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $data = $request->all();
        $product = Product::findOrFail($id);

        if ($request->file('image') == null) {
            $data['image'] = $product->image;
        } else{
            $data['image'] = $request->file('image')->store('assets/product', 'public');
        }

        $product->update($data);

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Product::findOrFail($id);

        $item->delete();

        return redirect()->route('product.index');
    }
}

resources/views/pages/product/create.blade.php
@extends('layouts.app')

@section('title')
    Homepage
@endsection

@section('content')
<main>
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
            
        @endif
        <h1 class="mt-4">Tambah Produk</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Tambah Produk</li>
        </ol>
        <div class="card">
            <div class="card-body">
                Tambah Produk
            </div>
        </div>
        <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label for="name">Produk</label>
              <input type="text" name="name" class="form-control" placeholder="Input Produk">

              <label for="kategori">Kategori</label>
              <select class="form-control" name="kategori">
                  <option>Makanan</option>
                  <option>Kue</option>
                  <option>Peralatan</option>
                </select>

                
              <label for="image" class="col-2 col-form-label">Photo</label>
              <input class="form-control" type="file" name="image" for="image">

              <label for="example-number-input" class="col-2 col-form-label">Jumlah Produk</label>
              
              <input class="form-control" type="number" name="jumlah" value="42" id="example-number-input">
              <label for="exampleInputHarga">Harga</label>
              <input type="number" name="harga" class="form-control" id="exampleInputHargaProduk" placeholder="Input Harga Produk">
              <label for="exampleInputKeterangan">Keterangan</label>
              <input type="text" name="keterangan" class="form-control" id="exampleInputEmail" placeholder="Input Keterangan Produk">
              
            </div>
              <button type="submit" class="btn btn-primary py-2">Save</a>
          </form>
    </div>
</main>
@endsection

resources/views/pages/product/edit.blade.php
@extends('layouts.app')

@section('title')
    Homepage
@endsection

@section('content')
<main>
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
            
        @endif
        <h1 class="mt-4">Tambah Produk</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit Produk</li>
        </ol>
        <div class="card">
            <div class="card-body">
                Tambah Produk
            </div>
        </div>
        <form action="{{ route('product.update', $item->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
              <label for="name">Produk</label>
              <input type="text" name="name" class="form-control" value="{{ $item->name }}">

              <label for="kategori">Kategori</label>
              <select class="form-control" name="kategori">
                  <option value="{{ $item->kategori }}">{{ $item->kategori }}</option>
                  <option>Makanan</option>
                  <option>Kue</option>
                  <option>Peralatan</option>
                </select>

                
              <label for="image" class="col-2 col-form-label">Photo</label>
              <input class="form-control" type="file" name="image" for="image">

              <label for="example-number-input" class="col-2 col-form-label">Jumlah Produk</label>
              
              <input class="form-control" type="number" name="jumlah" value="{{ $item->jumlah }}" id="example-number-input">
              <label for="exampleInputHarga">Harga</label>
              <input type="number" name="harga" class="form-control" id="exampleInputHargaProduk" value="{{ $item->harga }}">
              <label for="exampleInputKeterangan">Keterangan</label>
              <input type="text" name="keterangan" class="form-control" id="exampleInputEmail" value="{{ $item->keterangan }}">
              
            </div>
              <button type="submit" class="btn btn-primary py-2">Save</a>
          </form>
    </div>
</main>
@endsection

resources/views/pages/product/index.blade.php
@extends('layouts.app')

@section('title')
    Homepage
@endsection

@section ('content')
<main>
     <div class="container-fluid">
        <h1 class="mt-4">Produk</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Produk</li>
        </ol>
        <div class="card mb-4">
            <div class="card-body">
                <a href="{{ route('product.create') }}" class="btn btn-primary stretched-link">Tambah Produk</a>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                DataTable Example
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Produk</th>
                                <th>Kategori</th>
                                <th>Jumlah</th>
                                <th>Harga</th>
                                <th>Keterangan</th>
                                <th>Image</th>
                                <th>Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)
                            <tr>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->kategori }}</td>
                                <td>{{ $product->jumlah }}</td>
                                <td>{{ $product->harga }}</td>
                                <td>{{ $product->keterangan }}</td>
                                <td><img src="{{ Storage::url($product->image) }}" style="width: 100px;" alt=""></td>
                                <td><a href="{{ route('product.edit', $product->id) }}" type="button" class="btn btn-warning">Update</a>
                                    <form method="POST" action="{{ route('product.destroy', $product->id )}}">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">
                                    DELETE</button>
                                    </form>
                                    </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection    